#!/usr/bin/php
<?php

use Symfony\Component\Console\Application;

require __DIR__ . '/index.php';

$application = new Application();
$application->add(new SophyGenerator\Factory\SophyGeneratorCommand($app));
$application->run();
